version: '3.5'

services:

  mysql:
    image: mysql
    container_name: mysql_ms_patient
    environment:
      MYSQL_DATABASE: ms-patient
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

    ports:
      - 8080:8889
    volumes:
      - mysql_db:/data/db

volumes:

  mysql_db: